-- Run in Supabase SQL editor
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 90),
  body text not null check (char_length(body) between 3 and 1200),
  image_url text,
  flagged boolean not null default false,
  author_id uuid,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;

create policy "Public read posts"
on public.posts for select
using (true);

create policy "Anonymous insert posts"
on public.posts for insert
with check (true);

create policy "Moderator update flags"
on public.posts for update
using (
  auth.jwt() -> 'user_metadata' ->> 'role' in ('admin', 'moderator')
)
with check (
  auth.jwt() -> 'user_metadata' ->> 'role' in ('admin', 'moderator')
);
